# House Price Prediction Project

###  Problem Definition
- Goal: predict the sales price for each house
 
### Feature Selection
- Choose feature to train ML model
- Need to use `Feature Engineering` to identify Feature needed
 
### Spliting the Dataset
- `data` : dataset
- `x` : data[feature]
- `y` : target variable `SalePrice`

##### X,y -> X_train,X-test,  y_train, y_test

### Training ML model

### Model Evaluation

In [45]:
import pandas as pd
import numpy as np

In [46]:
data=pd.read_csv('train House Price Predict.csv')
data.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [47]:
data=pd.read_csv('train House Price Predict.csv',index_col="Id")

In [48]:
data.head()

MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
Id                                                                    
1           60       RL         65.0     8450   Pave   NaN      Reg   
2           20       RL         80.0     9600   Pave   NaN      Reg   
3           60       RL         68.0    11250   Pave   NaN      IR1   
4           70       RL         60.0     9550   Pave   NaN      IR1   
5           60       RL         84.0    14260   Pave   NaN      IR1   

   LandContour Utilities LotConfig  ... PoolArea PoolQC Fence MiscFeature  \
Id                                  ...                                     
1          Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
2          Lvl    AllPub       FR2  ...        0    NaN   NaN         NaN   
3          Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
4          Lvl    AllPub    Corner  ...        0    NaN   NaN         NaN   
5          Lvl    AllPub       FR2  ...        0    NaN   NaN         NaN   

   MiscVal MoSold  YrSold  SaleType  SaleCondition  SalePrice  
Id                                                             
1        0      2    2008        WD         Normal     208500  
2        0      5    2007        WD         Normal     181500  
3        0      9    2008        WD         Normal     223500  
4        0      2    2006        WD        Abnorml     140000  
5        0     12    2008        WD         Normal     250000  

[5 rows x 80 columns]

In [49]:
data.columns

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea',
       'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC',
       'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd',
       'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt',
       'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond',
       'PavedDrive', 'Wo

### Feature Selection 

In [50]:
features = ["LotArea","YearBuilt","1stFlrSF",'2ndFlrSF','FullBath','BedroomAbvGr','TotalBsmtSF']

### Spliting the Dataset into X and y

In [51]:
X=data[features]
y=data['SalePrice']

In [52]:
X.head()

LotArea  YearBuilt  1stFlrSF  2ndFlrSF  FullBath  BedroomAbvGr  \
Id                                                                   
1      8450       2003       856       854         2             3   
2      9600       1976      1262         0         2             3   
3     11250       2001       920       866         2             3   
4      9550       1915       961       756         1             3   
5     14260       2000      1145      1053         2             4   

    TotalBsmtSF  
Id               
1           856  
2          1262  
3           920  
4           756  
5          1145

In [53]:
y.head()

Id
1    208500
2    181500
3    223500
4    140000
5    250000
Name: SalePrice, dtype: int64

In [54]:
from sklearn.model_selection import train_test_split

X_train,X_valid,y_train,y_valid=train_test_split(X,y,train_size=0.8,random_state=0)

###  Trainning machine learning model

In [55]:
from sklearn.tree import DecisionTreeRegressor

dt_model=DecisionTreeRegressor(random_state=1)

In [56]:
#fit training data into model
dt_model.fit(X_train,y_train)

DecisionTreeRegressor(random_state=1)

In [78]:
y_predict=dt_model.predict(X_valid)
y_predict

array([180000., 159434., 109700., 207500., 112000., 108480., 232600.,
       119500., 755000., 156932., 254000., 150900., 214000., 130000.,
       155000., 150750., 215000., 126000., 174900., 128000., 145000.,
       149000., 138500., 189000., 139000., 106000., 173000.,  92000.,
       426000., 135000., 125000., 178000., 123000., 258000., 253293.,
       172785., 209500., 130000., 222500., 315750., 237500., 174000.,
       203000., 312500., 333168., 125000., 119000., 130000., 160000.,
       116000., 328000., 149900., 161500., 128500., 184000.,  62383.,
       124000., 227875., 155000., 110000., 140000., 136500., 141000.,
       154000., 180500., 174000., 144000., 252678.,  78000., 230000.,
       176000.,  67000., 116000., 210000., 116000., 250000., 132500.,
        96500., 325300., 179900., 143000., 120500., 127000., 147000.,
       228950., 194700., 108000., 196000., 208300., 141000., 188000.,
       130500., 183000., 210000., 215000., 145000., 190000., 127000.,
        88000., 1695

In [79]:
# show dataframe columns{y and y_predict}
pd.DataFrame({'y':y_valid,'y_predict':y_predict})

y  y_predict
Id                     
530   200624   180000.0
492   133000   159434.0
460   110000   109700.0
280   192000   207500.0
656    88000   112000.0
...      ...        ...
327   324000   257000.0
441   555000   611657.0
1388  136000   112000.0
1324   82500    80000.0
62    101000   116900.0

[292 rows x 2 columns]

In [59]:
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor

rf_model=RandomForestRegressor(random_state=1)
rf_model.fit(X_train,y_train)

RandomForestRegressor(random_state=1)

In [60]:
rf_val_preds=rf_model.predict(X_valid)

In [61]:
rf_val_preds[:5]

array([274168.51      , 141480.36      , 112840.43      , 196689.        ,
        89683.22333333])

###  Predict with a new input

In [62]:
X_valid.head()

LotArea  YearBuilt  1stFlrSF  2ndFlrSF  FullBath  BedroomAbvGr  \
Id                                                                    
530    32668       1957      2515         0         3             4   
492     9490       1941       958       620         1             3   
460     7015       1950       979       224         1             3   
280    10005       1977      1156       866         2             4   
656     1680       1971       525       567         1             3   

     TotalBsmtSF  
Id                
530         2035  
492          806  
460          709  
280         1160  
656          525

In [68]:
rf_model.predict([[6969,2021,1000,800,4,5,8]])

/home/thanhlong/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([198436.2])

### 5. Model Evaluation