In [1]:
import numpy as np

ModuleNotFoundError: No module named 'cv2'

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
[3.14,4,2,3]

[3.14, 4, 2, 3]

In [5]:
np.array([3.14,4,2,3])

array([3.14, 4.  , 2.  , 3.  ])

In [6]:
np.array([1,2,3,4],dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [7]:
a1=np.array([1,2,3,4])

In [8]:
type(a1)

numpy.ndarray

In [9]:
a2=np.array([[1,2,3],[4,5,6]])

In [10]:
type(a2)

numpy.ndarray

In [11]:
a2.shape

(2, 3)

In [12]:
a2.ndim #so chieu cua mang

2

In [13]:
a2.dtype

dtype('int64')

In [14]:
a2.size

6

# Create Numpy Arrays from Scratch
zeros, ones, full, arange, linspace

In [15]:
np.zeros([2,4],dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [16]:
 np.ones([3,5],dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
np.full([2,3],6.9,dtype=float)

array([[6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9]])

In [19]:
np.linspace(0,1,5) # tu 0 den 1, cach nhau 5 gia tri

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# random

In [20]:
np.random.random([4,4])

array([[0.34042353, 0.86772696, 0.34628181, 0.66117683],
       [0.66021228, 0.72144491, 0.62249239, 0.7082628 ],
       [0.57194244, 0.47672487, 0.05275204, 0.36570444],
       [0.92100127, 0.48817497, 0.11515026, 0.47958644]])

In [21]:
np.random.seed(0) #giu nguyen gia tri random
np.random.random([4,4])

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [22]:
np.random.normal(0,1,[3,3])

array([[ 0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ]])

In [23]:
np.random.randint(1,10,[5,6])

array([[8, 3, 1, 1, 5, 6],
       [6, 7, 9, 5, 2, 5],
       [9, 2, 2, 8, 4, 7],
       [8, 3, 1, 4, 6, 5],
       [5, 7, 5, 5, 4, 5]])

In [24]:
np.random.rand(4,4,4) # tao matrix voi 3 dimention [4x4x4]

array([[[0.58185033, 0.41436859, 0.4746975 , 0.6235101 ],
        [0.33800761, 0.67475232, 0.31720174, 0.77834548],
        [0.94957105, 0.66252687, 0.01357164, 0.6228461 ],
        [0.67365963, 0.971945  , 0.87819347, 0.50962438]],

       [[0.05571469, 0.45115921, 0.01998767, 0.44171092],
        [0.97958673, 0.35944446, 0.48089353, 0.68866118],
        [0.88047589, 0.91823547, 0.21682214, 0.56518887],
        [0.86510256, 0.50896896, 0.91672295, 0.92115761]],

       [[0.08311249, 0.27771856, 0.0093567 , 0.84234208],
        [0.64717414, 0.84138612, 0.26473016, 0.39782075],
        [0.55282148, 0.16494046, 0.36980809, 0.14644176],
        [0.56961841, 0.70373728, 0.28847644, 0.43328806]],

       [[0.75610669, 0.39609828, 0.89603839, 0.63892108],
        [0.89155444, 0.68005557, 0.44919774, 0.97857093],
        [0.11620191, 0.7670237 , 0.41182014, 0.67543908],
        [0.24979628, 0.31321833, 0.96541622, 0.58846509]]])

# Array Indexing & Slicing

In [25]:
x1=np.random.randint(20,size=6)

In [26]:
x1

array([19,  1,  8,  0,  4,  6])

In [27]:
x1[4],x1[0]

(4, 19)

# Multi-dimention array

In [28]:
x2=np.random.randint(10,size=[3,4])

In [29]:
x2

array([[5, 7, 8, 8],
       [9, 2, 8, 6],
       [6, 9, 1, 6]])

In [30]:
x2[0,1]=6

In [31]:
x2

array([[5, 6, 8, 8],
       [9, 2, 8, 6],
       [6, 9, 1, 6]])

# Slicing

In [32]:
x1

array([19,  1,  8,  0,  4,  6])

In [33]:
x1[0:3]

array([19,  1,  8])

In [34]:
x2[:2,:2]

array([[5, 6],
       [9, 2]])

# Reshaping of Array & Transpose

In [35]:
grid=np.arange(1,10)
grid.shape

(9,)

In [36]:
grid.reshape([3,3])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
x=np.array([1,2,3])

In [38]:
x.shape

(3,)

In [39]:
x.reshape([1,3]).shape

(1, 3)

In [40]:
x=np.array([[1,2],[3,4]])

In [41]:
x

array([[1, 2],
       [3, 4]])

In [42]:
x.T  # Transpose of x

array([[1, 3],
       [2, 4]])

# Array Concatenation and Splitting

In [43]:
x=np.array([1,2,3])
y=np.array([3,2,1])

In [44]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [45]:
grid=np.array([[1,2,3],
             [4,5,6]])

In [46]:
np.concatenate([grid,grid],axis=1)  #axis=0 by default

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [47]:
x=np.array([1,2,3])
grid=np.array([[9,8,7],[6,5,4]])

In [48]:
np.vstack([x,grid])  #vertical stack

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [49]:
y=np.array([[99],[99]])

In [50]:
np.hstack([y,grid]) #horizontal stack

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

# Spliting of arrays

In [51]:
x=np.array([1,2,3,99,69,3,2,1])

In [52]:
x1,x2,x3=np.split(x,[3,5])  # tach ra tu vi tri thu 3->4

In [53]:
x1

array([1, 2, 3])

In [54]:
x2

array([99, 69])

In [55]:
x3

array([3, 2, 1])

# Broadcasting and Vectorized operations 

In [57]:
a=np.arange(3) 

In [59]:
a

array([0, 1, 2])

In [62]:
a+5  #broadcasting

array([5, 6, 7])

In [64]:
b=np.ones([3,3])

In [65]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [67]:
a.shape,b.shape

((3,), (3, 3))

In [69]:
a+b

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [71]:
a*b 

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

In [73]:
c=np.arange(3).reshape([3,1])

In [75]:
c

array([[0],
       [1],
       [2]])

In [77]:
a+c

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

# Manipulating & Comparing Arrays 
Aggregation


In [78]:
list_number=[1,2,3]

In [80]:
ll=np.array(list_number)

In [81]:
ll

array([1, 2, 3])

In [83]:
sum(ll)

6

In [85]:
np.sum(ll)

6

In [87]:
massive_array=np.random.random(10000)

In [93]:
massive_array[:5]

array([0.94575707, 0.87776946, 0.38128803, 0.5411618 , 0.84596064])

In [96]:
%timeit sum(massive_array)
%timeit np.sum(massive_array) 

620 µs ± 4.33 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
5.81 µs ± 286 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [102]:
np.mean(massive_array)

0.49569502256425896

In [104]:
np.max(massive_array)

0.9999620173413053

In [107]:
np.min(massive_array)

0.00016644134026855273


# Do lech chuan va Phuong sai
# Standard Deviation & Variance

In [108]:
#np.std()
#np.va()

#std la do phan tan cua du lieu; ki hieu la phi (sigma) = [can bac 2 cua phuong sai(variance)]
#variance la trung binh cua binh phuong sai khac of mean(gia tri trung binh)

In [111]:
dog_height=[600,470,170,430,300]
dog_height=np.array(dog_height)

In [113]:
np.std(dog_height)

147.32277488562318

In [115]:
np.var(dog_height)

21704.0

In [117]:
np.sqrt(np.var(dog_height))

147.32277488562318

# Sorting Arrays
np.sort su dung quicksort algorithm

In [119]:
x=np.array([2,1,4,3,5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [121]:
np.argsort(x)  #return lai index cua cac preference

array([1, 0, 3, 2, 4])

In [123]:
np.random.seed(42)
MatA=np.random.randint(0,10,size=[4,6])

In [125]:
MatA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [127]:
np.sort(MatA,axis=0)  #sort theo cot

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [129]:
np.sort(MatA,axis=1) #sort theo hang

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

# Linear Algebra 

In [131]:
A=np.array([[1,2,3],
           [4,5,6],
           [7,8,9]])

In [132]:
B=np.array([[6,5],
           [4,3],
           [2,1]])

In [133]:
#A (3x3)  dot product B (3x2)
#dot product : tich vo huong

In [135]:
A.dot(B)  #nhu nhan 2 ma tran voi nhau

array([[20, 14],
       [56, 41],
       [92, 68]])

In [137]:
A@B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [139]:
B.T.dot(A)

array([[36, 48, 60],
       [24, 33, 42]])

In [142]:
B.T@A

array([[36, 48, 60],
       [24, 33, 42]])

In [145]:
#number of jars sold
np.random.seed(0)
sale_amounts = np.random.randint(0,20,[5,3])
sale_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [149]:
#Create weekly_sales DataFrame
import pandas as pd
weekly_sale = pd.DataFrame(sale_amounts,index=['Monday','Tueday','Wed','Thurs','Fri'],
                          columns=['Almond Butter','Peanut Butter','Cashew Butter'])

In [154]:
weekly_sale.head()

Almond Butter  Peanut Butter  Cashew Butter
Monday             12             15              0
Tueday              3              3              7
Wed                 9             19             18
Thurs               4              6             12
Fri                 1              6              7

In [157]:
#create a price array

prices=np.array([10,8,12])

In [166]:
butter_prices=pd.DataFrame(prices.reshape([1,3]),index=["Prices"],columns=['Almond Butter','Peanut Butter','Cashew Butter'])

In [168]:
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Prices             10              8             12

In [170]:
weekly_sale.shape, butter_prices.shape

((5, 3), (1, 3))

In [172]:
total_prices= weekly_sale@butter_prices.T

In [174]:
total_prices

Prices
Monday     240
Tueday     138
Wed        458
Thurs      232
Fri        142

In [176]:
weekly_sale['Total_price']=total_prices

In [177]:
weekly_sale

Almond Butter  Peanut Butter  Cashew Butter  Total_price
Monday             12             15              0          240
Tueday              3              3              7          138
Wed                 9             19             18          458
Thurs               4              6             12          232
Fri                 1              6              7          142